version: "3.8"

services:
  sample-redis:
    container_name: bs-sample-redis
    image: redis:6.0-alpine
    ports:
      - '6379:6379'
networks: 
  default: 
    external: 
# if required: docker network create bs-local-network
      name: bs-local-network
